# AlertManager configuration for IPE Platform
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@ipe.example.com'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'

# Templates for alert notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10m
  repeat_interval: 12h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 10s
      repeat_interval: 5m
    
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 1h
    
    - match:
        alertname: IPEApplicationDown
      receiver: 'application-down'
      group_wait: 5s
      repeat_interval: 2m

# Notification receivers
receivers:
  - name: 'default'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#ipe-monitoring'
        username: 'AlertManager'
        title: 'IPE Platform Alert'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'

  - name: 'critical-alerts'
    email_configs:
      - to: 'oncall@ipe.example.com'
        subject: '[CRITICAL] IPE Platform Alert'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}: {{ .Value }} {{ end }}
          {{ end }}
    
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#ipe-critical'
        username: 'AlertManager'
        title: '🚨 CRITICAL: IPE Platform Alert'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          {{ end }}
        color: 'danger'

  - name: 'warning-alerts'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#ipe-monitoring'
        username: 'AlertManager'
        title: '⚠️ WARNING: IPE Platform Alert'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          {{ end }}
        color: 'warning'

  - name: 'application-down'
    pagerduty_configs:
      - routing_key: '${PAGERDUTY_INTEGRATION_KEY}'
        description: 'IPE Application is down'
    
    email_configs:
      - to: 'oncall@ipe.example.com'
        subject: '[URGENT] IPE Application Down'
        body: |
          The IPE application is currently down and requires immediate attention.
          
          Time: {{ .CommonAnnotations.timestamp }}
          Duration: {{ .CommonLabels.for }}

# Inhibition rules
inhibit_rules:
  - source_match:
      alertname: 'IPEApplicationDown'
    target_match:
      job: 'ipe-api'
    equal: ['instance']

  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']